package ffcmd

import (
	"fmt"
	"os/exec"
	"strings"
)

// CreateOneSubSRTCmd is the command to create a SRT file which contains 1 subtitle only.
// It can be used to generate commands to create / remove a simple SRT file used in ffmpeg's subtitles filter.
type CreateOneSubSRTCmd struct {
	srtFile   string
	videoFile string
	text      string
	start     string
	end       string
}

// NewCreateOneSubSRTCmd returns a new command to create SRT file.
// srtFile: filename of the SRT file.
// videoFile: filename of video file to add subtitles.
// When end is empty, it'll try to get the duration of the video as end time.
// text: subtitle text.
// start, end: timestamp in the SRT file.
func NewCreateOneSubSRTCmd(srtFile, videoFile, text, start, end string) (*CreateOneSubSRTCmd, error) {
	if srtFile == "" {
		return nil, fmt.Errorf("empty SRT file name")
	}

	if text == "" {
		return nil, fmt.Errorf("empty subtitle text")
	}

	// Escape exclamation mark.
	text = strings.ReplaceAll(text, "!", `\!`)

	return &CreateOneSubSRTCmd{srtFile: srtFile, videoFile: videoFile, text: text, start: start, end: end}, nil
}

// NewCreateOneSubSRTCmdForImageClip returns a new command to create SRT file for a video generated by a image.
// srtFile: filename of the SRT file.
// text: subtitle text.
// duration: duration of the video generated by a image.
func NewCreateOneSubSRTCmdForImageClip(srtFile, text string, duration float32) (*CreateOneSubSRTCmd, error) {
	if duration <= 0 {
		return nil, fmt.Errorf("invalid duration")
	}

	start := "00:00:00,000"

	ts, err := NewTimestampFromSecond(duration)
	if err != nil {
		return nil, fmt.Errorf("NewTimestampFromSecond() error: %v", err)
	}
	end := ts.StringForSRT()

	return NewCreateOneSubSRTCmd(srtFile, "", text, start, end)
}

// String returns the command string to run.
func (cmd *CreateOneSubSRTCmd) String() (string, error) {
	var (
		err            error
		str            = ""
		tsStart, tsEnd *Timestamp
		start          = ""
		end            = ""
		startSec       float32
	)

	if cmd.start != "" {
		start = cmd.start
	} else {
		start = "00:00:00.000"
	}

	if tsStart, err = NewTimestamp(start); err != nil {
		return "", fmt.Errorf("invalid start time format")
	}

	startSec = tsStart.Second()

	if cmd.end == "" {
		if cmd.videoFile == "" {
			return "", fmt.Errorf("both end time and video filename are empty, can not get end timestamp")
		}

		str = fmt.Sprintf(`sec=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "%s"); sec=$(echo $sec - %.03f | bc); sec=$(echo $sec | awk -F. '{ print $1 }'); hh=$((sec / 3600)); mm=$((sec %% 3600 / 60)); ss=$((sec %% 3600 %% 60)); printf -v end "%%02d:%%02d:%%02d,000" $hh $mm $ss; echo -ne "1\n00:00:00,000 --> $end\n%s" > "%s"`, cmd.videoFile, startSec, cmd.text, cmd.srtFile)
	} else {
		if tsEnd, err = NewTimestamp(cmd.end); err != nil {
			return "", fmt.Errorf("invalid end time format")
		}

		if tsEnd, err = tsEnd.Sub(tsStart); err != nil {
			return "", fmt.Errorf("tsEnd.Sub() error: %v", err)
		}

		end = tsEnd.StringForSRT()

		str = fmt.Sprintf(`echo -ne "1\n00:00:00,000 --> %s\n%s" > "%s"`, end, cmd.text, cmd.srtFile)
	}

	return str, nil
}

// Command returns an exec.Cmd.
func (cmd *CreateOneSubSRTCmd) Command() (*exec.Cmd, error) {
	str, err := cmd.String()
	if err != nil {
		return nil, fmt.Errorf("cmd.String() error: %v", err)
	}

	return GenCommand(str)
}

// RemoveOneSubSRTCmd represents the command to remove a SRT file.
type RemoveOneSubSRTCmd struct {
	srtFile string
}

// NewRemoveOneSubSRTCmd returns a command to remove a SRT file.
// srtFile: filename of SRT file.
func NewRemoveOneSubSRTCmd(srtFile string) (*RemoveOneSubSRTCmd, error) {
	if srtFile == "" {
		return nil, fmt.Errorf("empty SRT filename")
	}

	return &RemoveOneSubSRTCmd{srtFile: srtFile}, nil
}

// String returns the commands string to run.
func (cmd *RemoveOneSubSRTCmd) String() (string, error) {
	return fmt.Sprintf(`rm "%s"`, cmd.srtFile), nil
}

// Command returns an exec.Cmd.
func (cmd *RemoveOneSubSRTCmd) Command() (*exec.Cmd, error) {
	str, err := cmd.String()
	if err != nil {
		return nil, fmt.Errorf("cmd.String() error: %v", err)
	}

	return GenCommand(str)
}
